name: Update Data Screener Otomatis

on:
  schedule:
    # Kembali ke jadwal 24 jam penuh untuk mengetes apakah alarm GitHub berfungsi
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
      # Mengatasi peringatan kuning Node.js (v3 diubah jadi v4)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Mengatasi peringatan kuning Node.js (v4 diubah jadi v5)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas numpy

      - name: Run update script
        run: python update_data.py

      - name: Commit and push changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action Bot"
          git add hasil_screener.csv
          git commit -m "Auto-update data saham" || echo "Tidak ada perubahan data"
          git push